language: cpp
git:
  depth: 3
env:
  global:
    # BINTRAY_KEY
    - secure: "WDcwmwVGvh2r07WLMf6dCNYCw+yY4j2huTEMjqPi1PmWWBwhzPogeUoaJRDIMW8JB6Iw9MOeGTuwbKkUQM0dQCYU/qdpIz4QkmqeKbi9d22wQhJYltcFGkA6vApKDXhnYhA2+8tiOOg5Q/2VCIAzb2pgcD/l92SwwJ0R2KvunWl0mOQIoL6bGb+1gpdekLLeLVL9XvXePthDY+9Pr1FMK0vO9iqzOEKzN4rMevkvvERcPFYV/zFH7ER8i8CT3TZPaLHDwCHWlrcv9e5iC/MIbZ+UKj+axFPEiFZudMWlhTN3oNPkJJCRzLSVYWnOMfOBhzoSBj3kQalznV6XeWoQWRQCZgWzUHVglXDcYfgyYelfXcVemNDEuscdiZXQgGLCVtDjTeug1a+IBgfCHPsUZC/MxDr/nX8TDLbWo/Xt38nIQLkWp+ZSG16kdK260QPP8PwAxrOo7oQDsZ1ySMZJQHDVoo/FLjOEuYswiQy5wnDPjtmgAllDtAKNvXfsBninu0K7jiMDC2Ff0B+hJFHnvYeQJ7QxRRaRhliAh0E/glmUv6rLD1L9ZgW7XlLvV0oMP8yOGTSjes7tsW7/NC0gDqED5KAdN614rDkm1peXeFFbmGGkB+5/UjmASexDEqRdOQdw51PKGn9D3FS12gA3vUEa5zi+6STNmUXs9vxjUfE="
matrix:
  include:
    - os: linux
      # I have to update to Ubuntu 16.04
      # since there is no Lua5.2 package for 14.04
      dist: xenial
      compiler: gcc
      addons:
        apt:
          packages:
            - libsdl2-dev
            - libsdl2-image-dev
            - libsdl2-mixer-dev
            - libfreetype6-dev
            - libcurl4-openssl-dev
            - libarchive-dev
            - liblua5.3-dev
            - desktop-file-utils
      after_success:
        - cd ..
        - git show -s HEAD > nightly-build-version.txt
        - wget -q https://github.com/AppImage/AppImages/raw/master/pkg2appimage -O ./pkg2appimage
        - chmod a+x ./pkg2appimage
        - export DOCKER_BUILD=1
        - bash -ex ./pkg2appimage ./pkg2appimage.yml
        - cd out
        - |
          for APPIMAGE in *.AppImage ; do
          curl -T $APPIMAGE "-uacmepjz:$BINTRAY_KEY" "https://api.bintray.com/content/acmepjz/meandmyshadow/meandmyshadow/nightly-build/$APPIMAGE?publish=1&override=1"
          done
    - os: osx
      compiler: clang
      install:
        - brew install sdl2 sdl2_image sdl2_mixer freetype libarchive lua
        - export PATH=/usr/local/opt/libarchive/bin:/usr/local/opt/libarchive/lib:/usr/local/opt/libarchive/include:$PATH
        # libcurl (xcode builtin)
script:
  - mkdir build && cd build && cmake .. && make
