language: cpp
git:
  depth: 3
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - libsdl2-dev
            - libsdl2-image-dev
            - libsdl2-ttf-dev
            - libsdl2-mixer-dev
            - libcurl4-openssl-dev
            - libarchive-dev
            - liblua5.2-dev
    - os: osx
      compiler: clang
      before_install:
        - brew install sdl2 sdl2image sdl2ttf sdl2mixer libarchive
        - export PATH=/usr/local/opt/libarchive/bin:/usr/local/opt/libarchive/lib:/usr/local/opt/libarchive/include:$PATH
        # libcurl (xcode builtin)
        # brew only has lua 5.1 and 5.3, so we need to compile it from source
        - export LUA52_VERSION=5.2.4
        - wget http://www.lua.org/ftp/lua-$LUA52_VERSION.tar.gz
        - tar zxf lua-$LUA52_VERSION.tar.gz
        - cd lua-$LUA52_VERSION && make macosx && sudo make install && cd ..
script:
  - mkdir build && cd build && cmake .. && make
