language: cpp
os: linux
compiler: gcc
git:
  depth: 10
addons:
  apt:
    packages:
      - libsdl1.2-dev
      - libsdl-image1.2-dev
      - libsdl-ttf2.0-dev
      - libsdl-mixer1.2-dev
      - libsdl-gfx1.2-dev
      - libcurl4-openssl-dev
      - libarchive-dev

script:
  - mkdir build && cd build && cmake .. && make
