version: 1.0.{build}
clone_depth: 10
shallow_clone: true
image:
  - Visual Studio 2013
platform: Win32
configuration:
  - Debug
  - Release
install:
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" set CMAKE_GENERATOR=Visual Studio 12 2013
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" set CMAKE_GENERATOR=Visual Studio 14 2015
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" set CMAKE_GENERATOR=Visual Studio 15 2017
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" set VSVERSION=VS2013
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" set VSVERSION=VS2015
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" set VSVERSION=VS2017
  # setup Visual Studio
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
  # we just download our prebuilt 3rdparty dependencies
  - set BINSUFFIX=%PLATFORM%-%VSVERSION%-%CONFIGURATION%
  - mkdir 3rdparty && cd 3rdparty
  - appveyor DownloadFile "https://github.com/acmepjz/meandmyshadow/releases/download/v0.5-devel001/3rdparty-%BINSUFFIX%.7z"
  - 7z x 3rdparty-%BINSUFFIX%.7z
  - cd ..
  - set PATH=%APPVEYOR_BUILD_FOLDER%\3rdparty;%PATH%
artifacts:
  - path: 'binonly-$(BINSUFFIX).7z'
before_build:
  - mkdir build && cd build
  - cmake -G "%CMAKE_GENERATOR%" -D "LUA_INCLUDE_DIR=%APPVEYOR_BUILD_FOLDER%\3rdparty" ..
build:
  project: build\meandmyshadow.sln
  verbosity: normal
after_build:
  # now we try to package the binary
  - cd /d %APPVEYOR_BUILD_FOLDER%
  - echo %APPVEYOR_BUILD_FOLDER%\3rdparty\*.dll > lst.txt
  - echo %APPVEYOR_BUILD_FOLDER%\build\%CONFIGURATION%\*.exe >> lst.txt
  - 7z a -t7z -mx=9 "binonly-%BINSUFFIX%.7z" @lst.txt
