version: 1.0.{build}
clone_depth: 10
shallow_clone: true
image:
  - Visual Studio 2013
  - Visual Studio 2015
platform: Win32
configuration:
  - Debug
  - Release
install:
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" set CMAKE_GENERATOR=Visual Studio 12 2013
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" set CMAKE_GENERATOR=Visual Studio 14 2015
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" set CMAKE_GENERATOR=Visual Studio 15 2017
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" set VSVERSION=VS2013
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" set VSVERSION=VS2015
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" set VSVERSION=VS2017
  # SDL
  - ps: Start-FileDownload 'https://www.libsdl.org/release/SDL-devel-1.2.15-VC.zip'
  - 7z x SDL-devel-1.2.15-VC.zip
  - set PATH=%APPVEYOR_BUILD_FOLDER%\SDL-1.2.15\include;%APPVEYOR_BUILD_FOLDER%\SDL-1.2.15\lib\x86;%PATH%
  # SDL_image
  - ps: Start-FileDownload 'https://www.libsdl.org/projects/SDL_image/release/SDL_image-devel-1.2.12-VC.zip'
  - 7z x SDL_image-devel-1.2.12-VC.zip
  - set PATH=%APPVEYOR_BUILD_FOLDER%\SDL_image-1.2.12\include;%APPVEYOR_BUILD_FOLDER%\SDL_image-1.2.12\lib\x86;%PATH%
  # SDL_ttf
  - ps: Start-FileDownload 'https://www.libsdl.org/projects/SDL_ttf/release/SDL_ttf-devel-2.0.11-VC.zip'
  - 7z x SDL_ttf-devel-2.0.11-VC.zip
  # ???
  - del SDL_ttf-2.0.11\lib\x86\zlib1.dll
  - set PATH=%APPVEYOR_BUILD_FOLDER%\SDL_ttf-2.0.11\include;%APPVEYOR_BUILD_FOLDER%\SDL_ttf-2.0.11\lib\x86;%PATH%
  # SDL_mixer
  - ps: Start-FileDownload 'https://www.libsdl.org/projects/SDL_mixer/release/SDL_mixer-devel-1.2.12-VC.zip'
  - 7z x SDL_mixer-devel-1.2.12-VC.zip
  - set PATH=%APPVEYOR_BUILD_FOLDER%\SDL_mixer-1.2.12\include;%APPVEYOR_BUILD_FOLDER%\SDL_mixer-1.2.12\lib\x86;%PATH%
  # setup Visual Studio
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
  # SDL_gfx, need to compile from source
  - ps: Start-FileDownload 'http://www.ferzkopp.net/Software/SDL_gfx-2.0/SDL_gfx-2.0.26.tar.gz'
  - 7z x SDL_gfx-2.0.26.tar.gz && 7z x SDL_gfx-2.0.26.tar && cd SDL_gfx-2.0.26
  - echo project(SDL_gfx) > CMakeLists.txt
  - echo Find_Package(SDL REQUIRED) >> CMakeLists.txt
  - echo add_definitions(-DDLL_EXPORT) >> CMakeLists.txt
  - echo include_directories(${SDL_INCLUDE_DIR}) >> CMakeLists.txt
  - echo add_library(SDL_gfx SHARED SDL_framerate.c SDL_gfxBlitFunc.c SDL_gfxPrimitives.c SDL_imageFilter.c SDL_rotozoom.c) >> CMakeLists.txt
  - echo Target_Link_Libraries(SDL_gfx ${SDL_LIBRARY}) >> CMakeLists.txt
  - mkdir build && cd build
  - cmake -G "%CMAKE_GENERATOR%" ..
  - msbuild SDL_gfx.sln /target:SDL_gfx /p:Configuration=%CONFIGURATION%
  - cd ..\..
  - set PATH=%APPVEYOR_BUILD_FOLDER%\SDL_gfx-2.0.26;%APPVEYOR_BUILD_FOLDER%\SDL_gfx-2.0.26\build\%CONFIGURATION%;%PATH%
  # libcurl...
  - ps: Start-FileDownload 'https://bintray.com/artifact/download/vszakats/generic/curl-7.59.0-win32-mingw.zip'
  - 7z x curl-7.59.0-win32-mingw.zip
  # ???
  - cd curl-7.59.0-win32-mingw\lib && rename libcurl.dll.a libcurl.lib && cd ..\..
  - set PATH=%APPVEYOR_BUILD_FOLDER%\curl-7.59.0-win32-mingw\include;%APPVEYOR_BUILD_FOLDER%\curl-7.59.0-win32-mingw\lib;%PATH%
  # zlib...
  - ps: Start-FileDownload 'http://www.zlib.net/zlib1211.zip'
  - 7z x zlib1211.zip && cd zlib-1.2.11
  - mkdir build && cd build
  - cmake -G "%CMAKE_GENERATOR%" ..
  - msbuild zlib.sln /target:zlib /p:Configuration=%CONFIGURATION%
  # ???
  - copy zconf.h ..\zconf.h
  - cd ..\..
  - set PATH=%APPVEYOR_BUILD_FOLDER%\zlib-1.2.11;%APPVEYOR_BUILD_FOLDER%\zlib-1.2.11\build\%CONFIGURATION%;%PATH%
  # libarchive, need to compile from source (very slow)
  - cd ..
  - git clone --depth 3 https://github.com/libarchive/libarchive.git
  - cd libarchive
  - mkdir builddd && cd builddd
  - cmake -G "%CMAKE_GENERATOR%" ..
  - msbuild libarchive.sln /target:archive /p:Configuration=%CONFIGURATION%
  - cd /d %APPVEYOR_BUILD_FOLDER%
  - set PATH=%APPVEYOR_BUILD_FOLDER%\..\libarchive\libarchive;%APPVEYOR_BUILD_FOLDER%\..\libarchive\builddd\libarchive\%CONFIGURATION%;%PATH%
  # %APPVEYOR_BUILD_FOLDER%\..\libarchive\builddd\bin\%CONFIGURATION%;
  # lua5.2, need to compile from source
  - ps: Start-FileDownload 'http://www.lua.org/ftp/lua-5.2.4.tar.gz'
  - 7z x lua-5.2.4.tar.gz && 7z x lua-5.2.4.tar && cd lua-5.2.4\src
  - echo project(lua52) > CMakeLists.txt
  - echo add_definitions(-DLUA_BUILD_AS_DLL) >> CMakeLists.txt
  - echo add_library(lua52 SHARED lapi.c lcode.c lctype.c ldebug.c ldo.c ldump.c lfunc.c lgc.c llex.c lmem.c lobject.c lopcodes.c lparser.c lstate.c lstring.c ltable.c ltm.c lundump.c lvm.c lzio.c lauxlib.c lbaselib.c lbitlib.c lcorolib.c ldblib.c liolib.c lmathlib.c loslib.c lstrlib.c ltablib.c loadlib.c linit.c) >> CMakeLists.txt
  - mkdir build && cd build
  - cmake -G "%CMAKE_GENERATOR%" ..
  - msbuild lua52.sln /target:lua52 /p:Configuration=%CONFIGURATION%
  # ??????
  - copy %CONFIGURATION%\lua52.lib %CONFIGURATION%\lua.lib
  - cd ..\..\..
  - set PATH=%APPVEYOR_BUILD_FOLDER%\lua-5.2.4\src;%APPVEYOR_BUILD_FOLDER%\lua-5.2.4\src\build\%CONFIGURATION%;%PATH%
  # ???
  # - set LUA_INCLUDE_DIR=%APPVEYOR_BUILD_FOLDER%\lua-5.2.4\src
  # now we try to package 3rdparty libraries, for simplicity we put the header and binary together
  - set BINSUFFIX=%PLATFORM%-%VSVERSION%-%CONFIGURATION%
  - echo %APPVEYOR_BUILD_FOLDER%\SDL_gfx-2.0.26\build\%CONFIGURATION%\*.dll > lst.txt
  - echo %APPVEYOR_BUILD_FOLDER%\SDL_gfx-2.0.26\build\%CONFIGURATION%\*.lib >> lst.txt
  - echo %APPVEYOR_BUILD_FOLDER%\SDL_gfx-2.0.26\build\%CONFIGURATION%\*.pdb >> lst.txt
  - echo %APPVEYOR_BUILD_FOLDER%\SDL_gfx-2.0.26\*.h >> lst.txt
  - echo %APPVEYOR_BUILD_FOLDER%\zlib-1.2.11\build\%CONFIGURATION%\*.dll >> lst.txt
  - echo %APPVEYOR_BUILD_FOLDER%\zlib-1.2.11\build\%CONFIGURATION%\*.lib >> lst.txt
  - echo %APPVEYOR_BUILD_FOLDER%\zlib-1.2.11\build\%CONFIGURATION%\*.pdb >> lst.txt
  - echo %APPVEYOR_BUILD_FOLDER%\zlib-1.2.11\*.h >> lst.txt
  - echo %APPVEYOR_BUILD_FOLDER%\..\libarchive\builddd\libarchive\bin\%CONFIGURATION%\*.dll >> lst.txt
  - echo %APPVEYOR_BUILD_FOLDER%\..\libarchive\builddd\libarchive\%CONFIGURATION%\*.lib >> lst.txt
  - echo %APPVEYOR_BUILD_FOLDER%\..\libarchive\builddd\libarchive\bin\%CONFIGURATION%\*.pdb >> lst.txt
  - echo %APPVEYOR_BUILD_FOLDER%\..\libarchive\libarchive\*.h >> lst.txt
  - echo %APPVEYOR_BUILD_FOLDER%\lua-5.2.4\src\build\%CONFIGURATION%\*.dll >> lst.txt
  - echo %APPVEYOR_BUILD_FOLDER%\lua-5.2.4\src\build\%CONFIGURATION%\*.lib >> lst.txt
  - echo %APPVEYOR_BUILD_FOLDER%\lua-5.2.4\src\build\%CONFIGURATION%\*.pdb >> lst.txt
  - echo %APPVEYOR_BUILD_FOLDER%\lua-5.2.4\src\*.h >> lst.txt
  - echo %APPVEYOR_BUILD_FOLDER%\SDL-1.2.15\lib\x86\*.dll >> lst.txt
  - echo %APPVEYOR_BUILD_FOLDER%\SDL-1.2.15\lib\x86\*.lib >> lst.txt
  - echo %APPVEYOR_BUILD_FOLDER%\SDL-1.2.15\include\*.h >> lst.txt
  - echo %APPVEYOR_BUILD_FOLDER%\SDL_image-1.2.12\lib\x86\*.dll >> lst.txt
  - echo %APPVEYOR_BUILD_FOLDER%\SDL_image-1.2.12\lib\x86\*.lib >> lst.txt
  - echo %APPVEYOR_BUILD_FOLDER%\SDL_image-1.2.12\include\*.h >> lst.txt
  - echo %APPVEYOR_BUILD_FOLDER%\SDL_ttf-2.0.11\lib\x86\*.dll >> lst.txt
  - echo %APPVEYOR_BUILD_FOLDER%\SDL_ttf-2.0.11\lib\x86\*.lib >> lst.txt
  - echo %APPVEYOR_BUILD_FOLDER%\SDL_ttf-2.0.11\include\*.h >> lst.txt
  - echo %APPVEYOR_BUILD_FOLDER%\SDL_mixer-1.2.12\lib\x86\*.dll >> lst.txt
  - echo %APPVEYOR_BUILD_FOLDER%\SDL_mixer-1.2.12\lib\x86\*.lib >> lst.txt
  - echo %APPVEYOR_BUILD_FOLDER%\SDL_mixer-1.2.12\include\*.h >> lst.txt
  - echo %APPVEYOR_BUILD_FOLDER%\curl-7.59.0-win32-mingw\bin\*.dll >> lst.txt
  - echo %APPVEYOR_BUILD_FOLDER%\curl-7.59.0-win32-mingw\bin\*.crt >> lst.txt
  - echo %APPVEYOR_BUILD_FOLDER%\curl-7.59.0-win32-mingw\lib\*.lib >> lst.txt
  - echo %APPVEYOR_BUILD_FOLDER%\curl-7.59.0-win32-mingw\include\*.h >> lst.txt
  - 7z a -t7z -mx=9 "3rdparty-%BINSUFFIX%.7z" @lst.txt
artifacts:
  - path: '3rdparty-$(BINSUFFIX).7z'
  - path: 'binonly-$(BINSUFFIX).7z'
before_build:
  - mkdir build && cd build
  - cmake -G "%CMAKE_GENERATOR%" -D "LUA_INCLUDE_DIR=%APPVEYOR_BUILD_FOLDER%\lua-5.2.4\src" ..
build:
  project: build\meandmyshadow.sln
  verbosity: normal
after_build:
  # now we try to package the binary
  - cd /d %APPVEYOR_BUILD_FOLDER%
  - echo %APPVEYOR_BUILD_FOLDER%\SDL_gfx-2.0.26\build\%CONFIGURATION%\*.dll > lst.txt
  - echo %APPVEYOR_BUILD_FOLDER%\zlib-1.2.11\build\%CONFIGURATION%\*.dll >> lst.txt
  - echo %APPVEYOR_BUILD_FOLDER%\..\libarchive\builddd\libarchive\%CONFIGURATION%\*.dll >> lst.txt
  - echo %APPVEYOR_BUILD_FOLDER%\lua-5.2.4\src\build\%CONFIGURATION%\*.dll >> lst.txt
  - echo %APPVEYOR_BUILD_FOLDER%\SDL-1.2.15\lib\x86\*.dll >> lst.txt
  - echo %APPVEYOR_BUILD_FOLDER%\SDL_image-1.2.12\lib\x86\*.dll >> lst.txt
  - echo %APPVEYOR_BUILD_FOLDER%\SDL_ttf-2.0.11\lib\x86\*.dll >> lst.txt
  - echo %APPVEYOR_BUILD_FOLDER%\SDL_mixer-1.2.12\lib\x86\*.dll >> lst.txt
  - echo %APPVEYOR_BUILD_FOLDER%\curl-7.59.0-win32-mingw\bin\*.dll >> lst.txt
  - echo %APPVEYOR_BUILD_FOLDER%\curl-7.59.0-win32-mingw\bin\*.crt >> lst.txt
  - echo %APPVEYOR_BUILD_FOLDER%\build\%CONFIGURATION%\*.exe >> lst.txt
  - 7z a -t7z -mx=9 "binonly-%BINSUFFIX%.7z" @lst.txt
